import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuroraBackground } from "@/components/ui/aurora-background";

const inter = Inter();

export const metadata: Metadata = {
  title: "Gustavo Silva - Desenvolvedor Full Stack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <AuroraBackground>
          {children}
        </AuroraBackground>
      </body>
    </html>
  );
}
